api_platform:
    title: 'Memoweb'
    version: 2
    description: 'Portail des Sujets de Mémoires, Projets, Travaux et Stages de fin d´études au Pôle Santé (Université libre de Bruxelles)'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
    # Good defaults value for REST APIs
    defaults:
        stateless: true
        # Good cache defaults
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']        
    openapi:
        contact:
            name: 'Pôle Santé - Informatique'
            url: 'http://https/portail.ulb.be/pole-sante-informatique'
            email: 'support@ulb.be'
